# Get editor completions based on the config schema
# "$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """\
$os\
$username on $hostname in $directory\
$git_branch\
$git_status\
$git_state\
$git_metrics\
$python\
$cmd_duration\
$line_break\
$character
"""
right_format = """\
$localip\
"""

[character] # The name of the module we are configuring is 'character'
format = '$symbol '
success_symbol = '[ ✔](bold green) '
error_symbol = '[ ✘](bold red) '
disabled = false


[cmd_duration]
style = "bold italic bright-blue"
min_time = 500 
format = " [](bold bright-purple) [$duration]($style)"

[directory]
truncation_length = 3
truncate_to_repo = true
fish_style_pwd_dir_length = 5
use_logical_path = false
format = '[$path]($style) [$read_only]($read_only_style)'
style = "bold italic purple"
disabled = false
read_only = ''    # 
read_only_style = 'bold red'
truncation_symbol = '.../'
home_symbol = '~'

[git_branch]
symbol = ""   #  
always_show_remote = false
only_attached = true
format = "on [$symbol $branch]($style)"
style = "bold italic bright-red"

[git_commit]
commit_hash_length = 8
style = "bold italic white"
tag_symbol = ' 󰓼 '
disabled = false

[git_metrics]
added_style = "bold green"
deleted_style = "bold red"
only_nonzero_diffs = true
ignore_submodules = true
format = ' [+$added]($added_style)/[-$deleted]($deleted_style) '
disabled = false

[git_state]
rebase = 'REBASING'
merge = 'MERGING'
revert = 'REVERTING'
cherry_pick = 'CHERRY-PICKING'
bisect = 'BISECTING'
am = 'AM'
am_or_rebase = 'AM/REBASE'
style = 'bold italic yellow'
format = '\([$state( $progress_current/$progress_total)]($style)\)'
disabled = false
# [git_state]
# format = '[$state( $progress_current $progress_total)]($style) '
# rebase = ''
# merge = ''
# revert = '󰁯'
# cherry_pick = ''
# bisect = '󰨯'
# am = '󰲾'
# am_or_rebase = '󰲾'
# disabled = false
[git_status]
ahead = " 󰶣${count}"    
behind = " 󰶡${count}"   
diverged = " 󰶣${ahead_count}󰶡${behind_count}"            
untracked = " ${count}" 
modified = " ${count}" 
renamed = " »${count}"  
conflicted = " ${count}"                                
deleted = " ✘${count}"  
staged = " 󱇬${count}"   
stashed = " ✔${count} "
typechanged = ' 󰄿${count} '
style = "bright-white"
format = """\
[$deleted](bold red)\
[$renamed](bold yellow)\
[$ahead_behind](bold green)\
[$stashed](bold green)\
[$conflicted](bold red)\
[$modified](bold blue)\
[$untracked](bold yellow)\
[$staged](bold green)\
"""

[hostname]
format = '[$ssh_symbol](bold italic bright-cyan)[$hostname]($style)'
ssh_only = false
ssh_symbol = " "
trim_at = ""
style = "bold italic blue"
disabled = false

[username]
show_always = true
style_user = "bold italic bright-purple"
style_root = "bold italic bright-red"
format = "[$user]($style)"

[os]
disabled = false
format = " $symbol  "

[os.symbols]
Alpaquita = ""
Alpine = ""
Amazon = ""
Android = ""
Arch = ""
Artix = ""
CentOS = ""
Debian = ""
DragonFly = ""
Emscripten = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = "󰛓"
Gentoo = ""
HardenedBSD = "󰞌"
Illumos = "󰈸"
Linux = ""
Mabox = ""
Macos = ""
Manjaro = ""
Mariner = ""
MidnightBSD = ""
Mint = ""
NetBSD = ""
NixOS = ""
OpenBSD = "󰈺"
openSUSE = ""
OracleLinux = "󰌷"
Pop = ""
Raspbian = ""
Redhat = ""
RedHatEnterprise = ""
Redox = "󰀘"
Solus = "󰠳"
SUSE = ""
Ubuntu = ""
Unknown = ""
Windows = "󰍲 "

[python]
disabled=false
format = '[ ${symbol}${pyenv_prefix}(${version})( \($virtualenv\)) ]($style)'
symbol = " "   # \ue606
version_format = "${raw}"
style = "bg:python fg:text_light"

[fill]
symbol = " "

[localip]
ssh_only = true
format = "[](bold purple)  [$localipv4](bold green) "
disabled = false 
